-- Crear tabla de lista de compras
CREATE TABLE IF NOT EXISTS `lista_compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `ingrediente_maestro_id` INT NOT NULL,
  `cantidad` DECIMAL(8, 2) NOT NULL,
  `unidad_medida_id` INT NOT NULL,
  `receta_id` INT NULL,
  `es_comprado` BOOLEAN NOT NULL DEFAULT false,
  `fecha_compra` TIMESTAMP(0) NULL,
  `prioridad` INT NOT NULL DEFAULT 1,
  `notas` VARCHAR(200) NULL,
  `precio_estimado` DECIMAL(8, 2) NULL,
  `tienda_sugerida` VARCHAR(100) NULL,
  `url_tienda` VARCHAR(500) NULL,
  `es_activo` BOOLEAN NOT NULL DEFAULT true,
  `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_usuario_lista` (`usuario_id`),
  INDEX `idx_ingrediente_lista` (`ingrediente_maestro_id`),
  INDEX `idx_comprado` (`es_comprado`),
  INDEX `idx_prioridad` (`prioridad`),
  INDEX `idx_fecha_lista` (`created_at`),
  CONSTRAINT `fk_lista_usuario` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_lista_ingrediente` FOREIGN KEY (`ingrediente_maestro_id`) REFERENCES `ingredientes_maestros` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_lista_unidad` FOREIGN KEY (`unidad_medida_id`) REFERENCES `unidades_medida` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_lista_receta` FOREIGN KEY (`receta_id`) REFERENCES `recetas` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
